server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mcp
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
