server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mcp
  jpa:
    hibernate:
      ddl-auto: create
  ai:
    mcp:
      ollama:
        base-url: http://localhost:11434
        chat:
          options:
            model: llama3